/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as AuthLayoutImport } from './routes/_auth/_layout'
import { Route as AuthLayoutInvoicesImport } from './routes/_auth/_layout/invoices'
import { Route as AuthLayoutIndexRouteImport } from './routes/_auth/_layout/index/route'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLayoutInvoicesRoute = AuthLayoutInvoicesImport.update({
  path: '/invoices',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutIndexRouteRoute = AuthLayoutIndexRouteImport.update({
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_auth/_layout/index/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout': {
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_layout/': {
      preLoaderRoute: typeof AuthLayoutIndexRouteImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/invoices': {
      preLoaderRoute: typeof AuthLayoutInvoicesImport
      parentRoute: typeof AuthLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LoginRouteRoute,
  AuthRoute.addChildren([
    AuthLayoutRoute.addChildren([
      AuthLayoutIndexRouteRoute,
      AuthLayoutInvoicesRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
