/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthLayoutImport } from './routes/_auth/_layout'
import { Route as AuthLayoutIndexImport } from './routes/_auth/_layout/index'
import { Route as AuthLayoutSettingsImport } from './routes/_auth/_layout/settings'
import { Route as AuthLayoutDashboardImport } from './routes/_auth/_layout/dashboard'
import { Route as AuthLayoutInvoicesIndexImport } from './routes/_auth/_layout/invoices.index'
import { Route as AuthLayoutClientsIndexImport } from './routes/_auth/_layout/clients.index'
import { Route as AuthLayoutInvoicesCreateImport } from './routes/_auth/_layout/invoices.create'
import { Route as AuthLayoutInvoicesIdImport } from './routes/_auth/_layout/invoices.$id'
import { Route as AuthLayoutClientsCreateImport } from './routes/_auth/_layout/clients.create'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLayoutIndexRoute = AuthLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutSettingsRoute = AuthLayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutDashboardRoute = AuthLayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_auth/_layout/dashboard.lazy').then((d) => d.Route),
)

const AuthLayoutInvoicesIndexRoute = AuthLayoutInvoicesIndexImport.update({
  path: '/invoices/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutClientsIndexRoute = AuthLayoutClientsIndexImport.update({
  path: '/clients/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutInvoicesCreateRoute = AuthLayoutInvoicesCreateImport.update({
  path: '/invoices/create',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutInvoicesIdRoute = AuthLayoutInvoicesIdImport.update({
  path: '/invoices/$id',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutClientsCreateRoute = AuthLayoutClientsCreateImport.update({
  path: '/clients/create',
  getParentRoute: () => AuthLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout': {
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_layout/dashboard': {
      preLoaderRoute: typeof AuthLayoutDashboardImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/settings': {
      preLoaderRoute: typeof AuthLayoutSettingsImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/': {
      preLoaderRoute: typeof AuthLayoutIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/clients/create': {
      preLoaderRoute: typeof AuthLayoutClientsCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/invoices/$id': {
      preLoaderRoute: typeof AuthLayoutInvoicesIdImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/invoices/create': {
      preLoaderRoute: typeof AuthLayoutInvoicesCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/clients/': {
      preLoaderRoute: typeof AuthLayoutClientsIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/invoices/': {
      preLoaderRoute: typeof AuthLayoutInvoicesIndexImport
      parentRoute: typeof AuthLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthLayoutRoute.addChildren([
      AuthLayoutDashboardRoute,
      AuthLayoutSettingsRoute,
      AuthLayoutIndexRoute,
      AuthLayoutClientsCreateRoute,
      AuthLayoutInvoicesIdRoute,
      AuthLayoutInvoicesCreateRoute,
      AuthLayoutClientsIndexRoute,
      AuthLayoutInvoicesIndexRoute,
    ]),
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
