version: '3.8'
services:
  client:
    build: .
    ports:
      - '8080:80'
    environment:
      - VITE_APP_API_URL=http://localhost:3005/api/v1
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '3005:3005'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/invoicing-app
      - PORT=3005
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27018:27017'
