version: '3.8'
services:
  client:
    build: .
    ports:
      - '8080:80'
    environment:
      - VITE_APP_API_URL=http://localhost:4005/api/v1
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '4005:4005'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/invoicing-app
      - PORT=4005
    volumes:
      - uploads:/app/uploads
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  uploads:
