name: Lint and Test Server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0

      - name: Change Directory and Install Dependencies
        run: |
          cd server
          npm ci

      - name: Lint Server
        run: |
          cd server
          npm run lint

      - name: Test Server
        run: |
          cd server
          npm test
