name: Server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache MongoDB binaries
        uses: actions/cache@v2
        with:
          path: |
            server/node_modules/.cache/mongodb-memory-server/mongodb-binaries
          key: ${{ runner.os }}-mongodb-binaries-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-mongodb-binaries-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0

      - name: Install Dependencies
        run: |
          cd server
          npm ci

      - name: Lint Server
        run: |
          cd server
          npm run lint

      - name: Test Server
        run: |
          cd server
          npm test
